"""Initial migration.

Revision ID: 3ce0fd982dfc
Revises: 
Create Date: 2024-09-20 17:20:45.142436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce0fd982dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chess_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('moves', sa.String(), nullable=True),
    sa.Column('game_status', sa.String(length=20), nullable=False),
    sa.Column('opening_phase', sa.Boolean(), nullable=False),
    sa.Column('player_color', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chess_game')
    # ### end Alembic commands ###
